[project]
name = "ta2025-hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gensim>=4.4.0",
    "jupyter>=1.1.1",
    "openai>=2.15.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "statsmodels>=0.14.6",
]
